### ISSUE TITLE
Hi there, I was just wondering if it's possible to do a transition animation with this?

### ISSUE THREAD

**Issue by dotdev-nikolaj** [mnsht/gradient-path#46]
I've got it working nicely by re-running gp.render but I was wondering if there's a way to animate the interpolation of keyframes other than manually rendering each exact position value perfectly? Thanks! 

Thanks a lot :D 

https://github.com/cereallarceny/gradient-path/assets/134979630/e49223ab-82a3-41c2-90d2-5e1d0c9cf604

**Comment by dotdev-nikolaj** [comment]
Oh sorry re-running `gp.render` is working but obviously causing a choppy look

Thanks !

**Comment by dotdev-nikolaj** [comment]
Don't mind the stretched out rectangle but yeah any idea how to make it smoothly transition if there is anyway? :O 

Uploading 21ea061098f6d555d3532c8d2fa8983c.mp4…

**Comment by dotdev-nikolaj** [comment]
I've kind of got it working by setting a delayed animation on all path-segments and selecting them via `:nth-child(Xn+i)` but the gradient doesn't seem to have a smooth transition.

Any help would be appreciated.

Not sure how the smooth transition of segments is being achieved on the path-segments... ?

Thanks! 

https://github.com/cereallarceny/gradient-path/assets/134979630/a8e4a19a-ceb2-4806-8d54-c6b71c2f74f3

<img width="523" alt="Screenshot 2023-07-04 at 11 34 47 pm" src="https://github.com/cereallarceny/gradient-path/assets/134979630/ed20f529-36fa-4292-90d0-68b19ea831d7">

**Comment by dotdev-nikolaj** [comment]
Repeated the red on either side to make it a little smoother but still not getting the gradient effect it has when using gradient-path on its own!


https://github.com/cereallarceny/gradient-path/assets/134979630/4255b798-3d68-4f15-a408-37e97fd50e2b

**Comment by dotdev-nikolaj** [comment]
Right well, we're close! Just need to do a little bit of interpolation and play with the j value.

I'm super tired so will tackle this tomorrow!

Peace and love all! ✌️☮️🌈

https://github.com/cereallarceny/gradient-path/assets/134979630/01248fd1-2c64-47ed-b3ec-dca92a44d221

https://github.com/cereallarceny/gradient-path/assets/134979630/951c075f-b518-4890-a99a-7bcc61f2c31f

<img width="647" alt="Screenshot 2023-07-04 at 11 46 33 pm" src="https://github.com/cereallarceny/gradient-path/assets/134979630/53707623-0467-4a68-b6b9-c7ef34de759b">

<img width="538" alt="Screenshot 2023-07-04 at 11 46 40 pm" src="https://github.com/cereallarceny/gradient-path/assets/134979630/1e07a618-288a-421c-b640-d031ddf73c13">

I'm super zoomed in in these videos by the way.

This is more what it looks like zoomed out and I included when the j value is a little low like < 200, it was > 500 in the above videos.

![Screenshot 2023-07-04 at 11 46 25 pm](https://github.com/cereallarceny/gradient-path/assets/134979630/808426f5-1ed9-4770-9a65-7c5a33668920)

**Comment by dotdev-nikolaj** [comment]
Well, I got it working by cloning this repo, importing it locally, and slightly modifying the `styleAttrs` function ! 

```
export const styleAttrs = (
  fill,
  stroke,
  strokeWidth,
  progress,
  animationName = "rainbow-psych",
  animationDuration = 5
) => {
  
    if (animationName) {
    // TODO: add animation-direction support
    attrs["style"] = `
      animation-name: ${animationName}; 
      animation-delay: ${progress * animationDuration - animationDuration}s;
      animation-duration: ${animationDuration}s; 
      animation-iteration-count: infinite; 
      animation-timing-function: linear;`
  }
```

Working really nicely! 

Thanks for making this awesome library :D 

I also added a `remove()` function to the `GradientPath.js` class for when resizing your svg with react useEffect callback.

```
  remove() {
    this.group.parentNode.removeChild(this.group)
  }
```

https://github.com/cereallarceny/gradient-path/assets/134979630/5790d23a-405e-4207-b2a0-75f813eacea3

**Comment by cereallarceny** [comment]
Looks like you got it working! Nice work. I'm sorry though, I can't offer support on this and I haven't meaningfully contributed to the library in many years. Closing this ticket due to the fact that I can't offer support.

**Comment by lopugit** [comment]
@cereallarceny haha no worries! 

Yes I did get it working in the end and it's AMAZING! Thanks heaps!!!!

**Comment by marcospassos** [comment]
Hey @lopugit, great work! Could you share a codepen with your example?
